### PR TITLE
Testing Full CVRF input

### PR DESCRIPTION
**Pull request by sustefil**
To provide a basic conversion coverage (and regression) test, we have a CVRF file with all possible elements (mandatory & optional), and asserting all of them in the CSAF output

### CODE REVIEW

**Comment by tschmidtb51** [comment]
@sustefil: Please do not use real domains here - use `example.com`, `example.net` and `example.org` where a domain name is needed.

**Comment by sustefil** [comment]
> @sustefil: Please do not use real domains here - use `example.com`, `example.net` and `example.org` where a domain name is needed.

Ah, sure, fixed :)

**Comment by cgi1** [comment]
Added: +1,452,132 lines 🤯 

Good that you added tons of examples due to the problems in schemata/standard and unsure circumstances around the testing procedure. Lets give our best here to test what has been implemented - And this is a good step forward!

**Comment by sustefil** [comment]
Closing as the "testing" branch will remain unmerged (many example files). Creating a new PR

**Pull request closed without merging**
