### PR TITLE
CS02 conformance implementation

### LINKED ISSUE #98: Correct implementation to conform CSD02
Here is a short list:
- [ ] make `ids` an array
- [ ] check on `/document/tracking/id` and remove whitespace
- [ ] add `legacy_number`

### PR DESCRIPTION
**Pull request by ir-dev**
Resolves #98

Besides the implementation todo's mentioned in the issue above to reach the conformance goal CS02, the following concerns have been addressed:
- File name creation according to CS02

- Replaced CSAF schemas (for CS02 schema validation of output files)

I also had to update the .gitignore file because it didn't seem to be set up properly.

### CODE REVIEW

**Comment by ir-dev** [comment]
I rechecked the normative requirements stated in the CVRF CSAF converter conformance rules, which changed from CS01 to CS02. There remain a few that may need to be discussed, although not necessarily relevant to the compliance objective and this converter tool (source: [Committee Specification 02 - Conformance Clause 5: CVRF CSAF converter](https://docs.oasis-open.org/csaf/csaf/v2.0/cs02/csaf-v2.0-cs02.html#915-conformance-clause-5-cvrf-csaf-converter)):
- `type /$defs/branches_t: If any prod:Branch instance has the type Realm or Resource, the CVRF CSAF converter replaces those with the category product_name. In addition, the converter outputs a warning that that those types do not exist in CSAF and have been replaced with the category product_name.`
This only seems relevant for CVRF 1.1 which this tool currently not supports either.

- `/document/lang: If one or more CVRF element containing an xml:lang attribute exist and contain the exact same value, the CVRF CSAF converter converts this value into lang. If the values of xml:lang attributes are not equal, the CVRF CSAF converter outputs a warning that the language could not be determined and possibly a document with multiple languages was produced. In addition, it SHOULD also present all values of xml:lang attributes as a set in the warning.`
Unfortunately I'm not too experienced in XML stuff and couldn't use an xml:lang attribute even though it should be a generic one (lxml XMLSchema validator returned "The attribute 'lang' is not allowed.") Is that how it's supposed to be?

-
  ```
  To determine, which minor version of CVSS v3 is used, the CVRF CSAF converter uses the following steps:
  1. Retrieve the CVSS version from the CVSS vector, if present.
  2. Retrieve the CVSS version from the CVSS element's namespace, if present. The CVRF CSAF converter outputs a warning that this value was guessed from the element's namespace.
  3. Retrieve the CVSS version from the CVSS namespace given in the root element, if present. The CVRF CSAF converter outputs a warning that this value was guessed from the global namespace. If more than one CVSS namespace is present and the element is not clearly defined via the namespace, this step MUST be skipped without a decision.
  4. Retrieve the CVSS version from a config value, which defaults to 3.0. (As CSAF CVRF v1.2 predates CVSS v3.1.) The CVRF CSAF converter outputs a warning that this value was taken from the config.
  ```
  Actually, this seems to be already implemented, but e.g. issuing warnings is done a bit differently than defined here.

**Comment by tschmidtb51** [comment]
@ir-dev Thank you for your contribution. It's really appreciated. Some minor comments before the full review:
- We try to use the links without the "os". (See your change in the README as they point to the latest version.)
- Please also update the links that point currently to csd02 or csd01 to the latest version (https://docs.oasis-open.org/csaf/csaf/v2.0/csaf-v2.0.html).

**Comment by tschmidtb51** [comment]
I'll do the full review as soon as I can.

**Comment by ir-dev** [comment]
> @ir-dev Thank you for your contribution. It's really appreciated. Some minor comments before the full review:
> 
> * We try to use the links without the "os". (See your change in the README as they point to the latest version.)
> * Please also update the links that point currently to csd02 or csd01 to the latest version (https://docs.oasis-open.org/csaf/csaf/v2.0/csaf-v2.0.html).

Done. If there is anything missing, please come back to me.

**Review by sthagen — APPROVED** [review]

**Review by tschmidtb51 — APPROVED** [review]
LGTM

**Comment by tschmidtb51** [comment]
> I rechecked the normative requirements stated in the CVRF CSAF converter conformance rules, which changed from CS01 to CS02. There remain a few that may need to be discussed, although not necessarily relevant to the compliance objective and this converter tool (source: [Committee Specification 02 - Conformance Clause 5: CVRF CSAF converter](https://docs.oasis-open.org/csaf/csaf/v2.0/cs02/csaf-v2.0-cs02.html#915-conformance-clause-5-cvrf-csaf-converter)):
> 
> * `type /$defs/branches_t: If any prod:Branch instance has the type Realm or Resource, the CVRF CSAF converter replaces those with the category product_name. In addition, the converter outputs a warning that that those types do not exist in CSAF and have been replaced with the category product_name.`
>   This only seems relevant for CVRF 1.1 which this tool currently not supports either.

The [prod XSD of CSAF CVRF 1.2](https://docs.oasis-open.org/csaf/csaf-cvrf/v1.2/cs01/schemas/prod.xsd) lists those two, even if the [specification](http://docs.oasis-open.org/csaf/csaf-cvrf/v1.2/cs01/csaf-cvrf-v1.2-cs01.html#_Toc493508797) does not. Therefore, the rule is needed.

>  * `/document/lang: If one or more CVRF element containing an xml:lang attribute exist and contain the exact same value, the CVRF CSAF converter converts this value into lang. If the values of xml:lang attributes are not equal, the CVRF CSAF converter outputs a warning that the language could not be determined and possibly a document with multiple languages was produced. In addition, it SHOULD also present all values of xml:lang attributes as a set in the warning.`
>       Unfortunately I'm not too experienced in XML stuff and couldn't use an xml:lang attribute even though it should be a generic one (lxml XMLSchema validator returned "The attribute 'lang' is not allowed.") Is that how it's supposed to be?

There is a separate issue for that. See https://github.com/csaf-tools/CVRF-CSAF-Converter/issues/84#issuecomment-1412997550 for more details.

>     * ```
>       To determine, which minor version of CVSS v3 is used, the CVRF CSAF converter uses the following steps:
>       1. Retrieve the CVSS version from the CVSS vector, if present.
>       2. Retrieve the CVSS version from the CVSS element's namespace, if present. The CVRF CSAF converter outputs a warning that this value was guessed from the element's namespace.
>       3. Retrieve the CVSS version from the CVSS namespace given in the root element, if present. The CVRF CSAF converter outputs a warning that this value was guessed from the global namespace. If more than one CVSS namespace is present and the element is not clearly defined via the namespace, this step MUST be skipped without a decision.
>       4. Retrieve the CVSS version from a config value, which defaults to 3.0. (As CSAF CVRF v1.2 predates CVSS v3.1.) The CVRF CSAF converter outputs a warning that this value was taken from the config.
>       ```
>       Actually, this seems to be already implemented, but e.g. issuing warnings is done a bit differently than defined here.

Feel free to open a separate issue for that.

**Pull request merged**
